framework:
  messenger:
    # The bus that is going to be injected when injecting MessageBusInterface
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - doctrine_transaction
          - App\Infrastructure\Messages\Messenger\Middleware\LogMessageMiddleware
      query.bus:
        middleware:
          - App\Infrastructure\Messages\Messenger\Middleware\LogMessageMiddleware